add_subdirectory(MCore_util)
add_subdirectory(MCore_interface)
add_subdirectory(MCore_database)
add_subdirectory(MCore_simulate)
add_subdirectory(MCore_render)
add_subdirectory(MCore_system)
add_subdirectory(MPS_database)
add_subdirectory(MPS_simulate)
add_subdirectory(MPS_system)
add_subdirectory(App)
